name: checks

on:
  push:
    branches: [master]
  pull_request:

jobs:
  rust:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: undivisible/crepuscularity
          path: crepuscularity
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: mv crepuscularity ../crepuscularity
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
